name: CICD_K8S

on:
  push:
    branches: [ "Dev" ]
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: Trivy File System Scan
      run: trivy fs --format table -o fs-scan.html .

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_URL }}

    - name: Set up QEMU (Docker)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker image build -t danish84464/devdanii:latest .

    - name: Trivy Docker Image Scan
      run: trivy image --format table -o image-scan.html danish84464/devdanii:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image to Docker Hub
      run: docker push danish84464/devdanii:latest
